### ISSUE TITLE
Auto-play results in max call stack exception

### ISSUE THREAD

**Issue by reddyalready** [socialgorithm/tournament-server#2]
When selecting "Play next set of games automatically", we get an infinite loop

Here's the exception:

```
/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:122
    if (this.matchmaker.isFinished()) {
                        ^
RangeError: Maximum call stack size exceeded
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:122:25)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
    at TournamentRunner.playNextMatch (/Users/bharat/code/sg/tournament-server/src/lobby/tournament/TournamentRunner.ts:131:12)
```

**Comment by reddyalready** [comment]
This was actually an issue with the FFA matchmaker. I have fixed that, and also fixed another autoplay bug in b8bfb9d34dd80c56654fd4e12f6b512cbb0b3b1a
